import streamlit as st
import pandas as pd
from datetime import datetime
from supabase import create_client, Client
import os

# ---------- CONFIGURACIÓN ----------
st.set_page_config(page_title="NewsBot Control Panel", layout="wide")

# Credenciales (usa secrets en producción, aquí con fallback local)
SUPABASE_URL = os.getenv("SUPABASE_URL", "https://vjtqhjykwqutxvrufgpv.supabase.co")
SUPABASE_SERVICE_ROLE_KEY = os.getenv(
    "SUPABASE_SERVICE_ROLE_KEY",
    "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZqdHFoanlrd3F1dHh2cnVmZ3B2Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3ODUyNDkwMCwiZXhwIjoyMDk0MTAwOTAwfQ.jhxHBIBE2liTHdD8WV2CyYSF9xx9Wxfl8HwJ4sXnhbo"
)
supabase: Client = create_client(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY)

# ---------- FUNCIONES AUXILIARES ----------
def tabla_existe(nombre_tabla):
    """Intenta seleccionar 0 filas para comprobar si existe la tabla."""
    try:
        supabase.table(nombre_tabla).select("*", count="exact").limit(0).execute()
        return True
    except Exception:
        return False

# ---------- INTERFAZ ----------
st.title("🤖 NewsBot Manager")
st.markdown("Gestión de noticias, anuncios y sincronización con GitHub.")

# Verificar existencia de tablas y mostrar ayuda si faltan
missing_tables = []
for tabla in ["noticias_publicadas", "anuncios_disponibles"]:
    if not tabla_existe(tabla):
        missing_tables.append(tabla)

if missing_tables:
    st.error(f"❌ **Faltan las siguientes tablas en tu base de datos:** `{', '.join(missing_tables)}`.")
    st.markdown("""
    ### 🔧 Crea las tablas en el **SQL Editor** de Supabase
    
    1. Ve a [SQL Editor](https://supabase.com/dashboard/project/vjtqhjykwqutxvrufgpv/sql)
    2. Pega y ejecuta **cada bloque** por separado:
    """)
    st.code("""
-- Tabla para noticias publicadas
CREATE TABLE IF NOT EXISTS public.noticias_publicadas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  noticia_hash TEXT NOT NULL UNIQUE,
  fecha_publicacion TIMESTAMPTZ DEFAULT NOW()
);

-- Tabla para anuncios
CREATE TABLE IF NOT EXISTS public.anuncios_disponibles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  texto_anuncio TEXT NOT NULL,
  imagen_url TEXT,
  link_afiliado TEXT,
  activo BOOLEAN DEFAULT TRUE
);
    """, language="sql")
    st.info("Después de crear las tablas, recarga esta página.")
    st.stop()  # detiene la ejecución para que no aparezcan más errores

# Si las tablas existen, continuar normalmente
tabs = st.tabs(["📈 Estadísticas", "📢 Gestionar Anuncios", "📰 Historial News", "⚙️ Configuración"])

# --- TAB 1: ESTADÍSTICAS ---
with tabs[0]:
    st.subheader("Rendimiento del Canal")
    try:
        count_resp = supabase.table("noticias_publicadas").select("*", count="exact").execute()
        total_news = count_resp.count if count_resp.count is not None else 0
        
        col1, col2, col3 = st.columns(3)
        col1.metric("Noticias Publicadas", total_news)
        col2.metric("Próximo Anuncio en", f"{10 - (total_news % 10)} posts")
        col3.metric("Estado del Bot", "Activo", delta="Online")
    except Exception as e:
        st.error(f"Error al conectar con Supabase: {e}")

# --- TAB 2: GESTIONAR ANUNCIOS ---
with tabs[1]:
    st.subheader("Agregar Nuevo Anuncio (Ad-Insertion)")
    with st.form("new_ad"):
        texto = st.text_area("Texto del Anuncio")
        img_url = st.text_input("URL de la Imagen")
        link_afi = st.text_input("Link de Afiliado/Referido")
        if st.form_submit_button("Guardar Anuncio"):
            try:
                anuncio = {
                    "texto_anuncio": texto,
                    "imagen_url": img_url,
                    "link_afiliado": link_afi,
                    "activo": True
                }
                supabase.table("anuncios_disponibles").insert(anuncio).execute()
                st.success("Anuncio guardado correctamente.")
            except Exception as e:
                st.error(f"Error al guardar: {e}")

    st.divider()
    st.subheader("Anuncios Activos")
    try:
        ads_resp = supabase.table("anuncios_disponibles")\
            .select("id, texto_anuncio, activo")\
            .execute()
        if ads_resp.data:
            df_ads = pd.DataFrame(ads_resp.data, columns=["id", "texto_anuncio", "activo"])
            st.dataframe(df_ads, use_container_width=True)
        else:
            st.info("No hay anuncios registrados.")
    except Exception as e:
        st.error(f"Error al cargar anuncios: {e}")

# --- TAB 3: HISTORIAL ---
with tabs[2]:
    st.subheader("Últimas Noticias Procesadas")
    try:
        news_resp = supabase.table("noticias_publicadas")\
            .select("id, noticia_hash, fecha_publicacion")\
            .order("fecha_publicacion", desc=True)\
            .limit(20)\
            .execute()
        if news_resp.data:
            df_news = pd.DataFrame(news_resp.data, columns=["id", "noticia_hash", "fecha_publicacion"])
            st.table(df_news)
        else:
            st.info("No hay noticias en el historial.")
    except Exception as e:
        st.error(f"Error al cargar historial: {e}")

# --- TAB 4: CONFIGURACIÓN ---
with tabs[3]:
    st.subheader("Sincronización con GitHub")
    st.info("El bot está configurado para leer 'TasaBCV.xlsx' desde tu repositorio.")
    if st.button("🔄 Forzar Sincronización GitHub"):
        st.warning("Enviando señal de actualización...")
        st.success("Repositorio sincronizado (simulado).")
    
    st.subheader("Logs del Sistema")
    st.code(f"{datetime.now().strftime('%Y-%m-%d %H:%M:%S')} - INFO - Panel accedido")
