import streamlit as st
import pandas as pd
from datetime import datetime
from supabase import create_client, Client
import os

# ---------- CONFIGURACIÓN ----------
st.set_page_config(page_title="NewsBot Control Panel", layout="wide")

# Lectura estricta de variables de entorno (Sin valores explícitos por seguridad)
SUPABASE_URL = os.getenv("SUPABASE_URL")
SUPABASE_SERVICE_ROLE_KEY = os.getenv("SUPABASE_SERVICE_ROLE_KEY")

# Validación temprana de credenciales de infraestructura
if not SUPABASE_URL or not SUPABASE_SERVICE_ROLE_KEY:
    st.error("❌ **Error de Configuración:** Faltan las variables de entorno `SUPABASE_URL` o `SUPABASE_SERVICE_ROLE_KEY`.")
    st.info("Por favor, asegúrate de configurar los Secrets en tu plataforma de despliegue antes de continuar.")
    st.stop()

# Inicialización segura del cliente de Supabase
supabase: Client = create_client(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY)

# ---------- FUNCIONES AUXILIARES ----------
def tabla_existe(nombre_tabla):
    """Intenta seleccionar 0 filas para comprobar si existe la tabla."""
    try:
        supabase.table(nombre_tabla).select("*", count="exact").limit(0).execute()
        return True
    except Exception:
        return False

# ---------- INTERFAZ ----------
st.title("🤖 NewsBot Manager")
st.markdown("Gestión de noticias, anuncios y sincronización con GitHub.")

# Verificar existencia de tablas y mostrar ayuda si faltan
missing_tables = []
for tabla in ["noticias_publicadas", "anuncios_disponibles", "contador_publicaciones"]:
    if not tabla_existe(tabla):
        missing_tables.append(tabla)

if missing_tables:
    st.error(f"❌ **Faltan las siguientes tablas en tu base de datos:** `{', '.join(missing_tables)}`.")
    st.markdown("""
    ### 🔧 Crea las tablas en el **SQL Editor** de Supabase
    
    1. Ve al panel de control de tu proyecto en Supabase y abre el **SQL Editor**.
    2. Pega y ejecuta el siguiente bloque de inicialización de la base de datos:
    """)
    st.code("""
-- Tabla para noticias publicadas
CREATE TABLE IF NOT EXISTS public.noticias_publicadas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  noticia_hash TEXT NOT NULL UNIQUE,
  categoria TEXT,
  fecha_publicacion TIMESTAMPTZ DEFAULT NOW()
);

-- Tabla para anuncios
CREATE TABLE IF NOT EXISTS public.anuncios_disponibles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  texto_anuncio TEXT NOT NULL,
  imagen_url TEXT,
  link_afiliado TEXT,
  activo BOOLEAN DEFAULT TRUE
);

-- Tabla para control de frecuencia de anuncios
CREATE TABLE IF NOT EXISTS public.contador_publicaciones (
    id SERIAL PRIMARY KEY,
    total_enviadas INTEGER DEFAULT 0
);

INSERT INTO public.contador_publicaciones (total_enviadas) VALUES (0);
    """, language="sql")
    st.info("Después de crear las tablas en Supabase, recarga esta página.")
    st.stop()  # detiene la ejecución para que no aparezcan más errores

# Si las tablas existen, continuar normalmente
tabs = st.tabs(["📈 Estadísticas", "📢 Gestionar Anuncios", "📰 Historial News", "⚙️ Configuración"])

# --- TAB 1: ESTADÍSTICAS ---
with tabs[0]:
    st.subheader("Rendimiento del Canal")
    try:
        count_resp = supabase.table("noticias_publicadas").select("*", count="exact").execute()
        total_news = count_resp.count if count_resp.count is not None else 0
        
        col1, col2, col3 = st.columns(3)
        col1.metric("Noticias Publicadas", total_news)
        col2.metric("Próximo Anuncio en", f"{10 - (total_news % 10)} posts")
        col3.metric("Estado del Bot", "Activo", delta="Online")
    except Exception as e:
        st.error(f"Error al conectar con Supabase: {e}")

# --- TAB 2: GESTIONAR ANUNCIOS ---
with tabs[1]:
    st.subheader("Agregar Nuevo Anuncio (Ad-Insertion)")
    with st.form("new_ad"):
        texto = st.text_area("Texto del Anuncio")
        img_url = st.text_input("URL de la Imagen")
        link_afi = st.text_input("Link de Afiliado/Referido")
        if st.form_submit_button("Guardar Anuncio"):
            try:
                anuncio = {
                    "texto_anuncio": texto,
                    "imagen_url": img_url,
                    "link_afiliado": link_afi,
                    "activo": True
                }
                supabase.table("anuncios_disponibles").insert(anuncio).execute()
                st.success("Anuncio guardado correctamente.")
            except Exception as e:
                st.error(f"Error al guardar: {e}")

    st.divider()
    st.subheader("Anuncios Activos")
    try:
        ads_resp = supabase.table("anuncios_disponibles")\
            .select("id, texto_anuncio, activo")\
            .execute()
        if ads_resp.data:
            df_ads = pd.DataFrame(ads_resp.data, columns=["id", "texto_anuncio", "activo"])
            st.dataframe(df_ads, use_container_width=True)
        else:
            st.info("No hay anuncios registrados.")
    except Exception as e:
        st.error(f"Error al cargar anuncios: {e}")

# --- TAB 3: HISTORIAL ---
with tabs[2]:
    st.subheader("Últimas Noticias Procesadas")
    try:
        news_resp = supabase.table("noticias_publicadas")\
            .select("id, noticia_hash, categoria, fecha_publicacion")\
            .order("fecha_publicacion", desc=True)\
            .limit(20)\
            .execute()
        if news_resp.data:
            df_news = pd.DataFrame(news_resp.data)
            st.dataframe(df_news, use_container_width=True)
        else:
            st.info("No hay noticias en el historial.")
    except Exception as e:
        st.error(f"Error al cargar historial: {e}")

# --- TAB 4: CONFIGURACIÓN ---
with tabs[3]:
    st.subheader("Sincronización con GitHub")
    st.info("El bot está configurado para leer 'TasaBCV.xlsx' desde tu repositorio.")
    if st.button("🔄 Forzar Sincronización GitHub"):
        st.warning("Enviando señal de actualización...")
        st.success("Repositorio sincronizado (simulado).")
    
    st.subheader("Logs del Sistema")
    st.code(f"{datetime.now().strftime('%Y-%m-%d %H:%M:%S')} - INFO - Panel accedido de forma segura.")
